#! /usr/bin/env bash
curdir=${0%/*}

base=$curdir/conky/base
if [ ! -f $base ]; then exit 1;
else conky -d -c $base; fi
sleep 1

maxim=$curdir/conky/maxim
if [ ! -f $maxim ]; then exit 1;
else conky -d -c $maxim; fi
sleep 1

weather=$curdir/conky/weather
if [ ! -f $weather ]; then exit 1;
else conky -d -c $weather; fi
