#! /usr/bin/env bash
curdir=${0%/*}

function conky_daemon() {
    conf="$curdir/conky/$1"
    if [ ! -f $conf ]; then exit 1;
    else conky -d -c $conf
    fi
    sleep 1
}

#conky_daemon footprint
#exit 0 # ignore other configs

conky_daemon status
conky_daemon maxim
conky_daemon weather
