#! /usr/bin/env bash
pandoc -V geometry:margin=1in -V author="ZhiQiang Fan"  -V date="`date '+%b %d %Y'`" -V monofont="Courier 10 Pitch" -V sansfont="FreeSans" -V mainfont="FreeMono" --latex-engine=xelatex --toc -V fontsize=12pt -o out.pdf "$@"
