#! /usr/bin/env bash

if [[ -s $HOME/.rvm/scripts/rvm ]]; then
    source $HOME/.rvm/scripts/rvm
    cur_dir=`pwd`
    cd $HOME/public/zqfan.github.com/
    jekyll --server 1>/tmp/jekylld.log 2>&1 &
    cd "$cur_dir"
fi
